### ISSUE TITLE
General Inquiry / Request for Windows release

### ISSUE THREAD

**Issue by DrewUniverse** [mcred/Dragoon-Editor#60]
## Problem

@mcred The current release appears to be for MacOS only. Most people who would use this tool are Windows-based, making this tool inaccessible (unfortunately). 

## Solution

I do not have a personal solution. I only hope that A. it would be simple enough to port, and B. you had the time and willingness. If not I totally understand. 

## Alternatives

One alternative would be to bring awareness of this tool to the LoD modding community on the LoD Discord server, whereby other developers could work on it and help with features/releases.

## Additional Info

I can be reached on Discord: DrewUniverse# 0108

**Comment by mcred** [comment]
@DrewUniverse The code is written in GoLang with a GUI framework that supports windows. It shouldn't be too difficult to package a windows release. I have built the app in windows and run it, but packaging it for release just isn't done yet. 

Do you do any development on windows?

I'll ping you on discord soon, but I'd prefer if we keep most of the conversation here in the open.

**Comment by DrewUniverse** [comment]
@mcred thank you for responding. It is great to learn that a Windows build is possible; I will pass it along to our community modders to see if any of them can create it. 

I do not develop/code for Windows or other platforms, no. I am a video game archivist primarily, and have done a lot of work on Dragoon to that end. One of our side-goals is to develop a savefile editor for the purposes of modding and accessibility.

**Comment by mcred** [comment]
I might be able to get a windows build to you soon. I'm revisiting some of the build tools for this project. It looks promising.

**Comment by mcred** [comment]
@DrewUniverse Here is (hopefully) a working [windows release](https://github.com/mcred/Dragoon-Editor/releases/tag/v0.0.10). It looks for a mednafen save file, but with some other examples of save files, more support could be added. Please let me know if this works for you.

**Comment by DrewUniverse** [comment]
@mcred confirmed functional with Mednafen-based savefiles generated from Retroarch/Beetle. It correctly loads the first save slot on a given card. It'll probably work with all Mednafen saves but we can get testers easily enough to make sure of it. 

Is this a project you're okay with being open-source? I'd love to see if we can get some volunteers on-board, so that any feature requests/additions don't have to be created by you specifically.

**Comment by mcred** [comment]
It's already open sourced with an MIT license. Anyone is free and encouraged to contribute in any way they can!
